// ─── CONSTANTS ───────────────────────────────────────────────────────────────
export const CAFES = ["Cafe 1", "Cafe 2", "Cafe 3", "Back of Cafe"];

export const HOSTELS = [
  "Joseph Hall",
  "Daniel Hall",
  "Abigail Hall",
  "Abraham Hall",
  "Sarah Hall",
  "Deborah Hall",
  "Jacob Hall",
];

export const PAYMENT_METHODS = [
  { id: "wallet", label: "LMU Wallet", icon: "💳", desc: "Pay from your campus e-wallet" },
  { id: "transfer", label: "Bank Transfer", icon: "🏦", desc: "Transfer to cafe account" },
  { id: "cash", label: "Cash on Delivery", icon: "💵", desc: "Pay when food arrives" },
];

export const INITIAL_MENU = {
  "Cafe 1": [
    {
      id: 1,
      name: "Jollof Rice + Chicken",
      price: 1200,
      time: 15,
      img: "🍛",
      tag: "Bestseller",
      available: true,
    },
    {
      id: 2,
      name: "Fried Rice + Fish",
      price: 1100,
      time: 12,
      img: "🍚",
      tag: "Popular",
      available: true,
    },
    {
      id: 3,
      name: "Amala + Ewedu",
      price: 900,
      time: 10,
      img: "🥣",
      tag: "",
      available: true,
    },
    {
      id: 4,
      name: "Egusi Soup + Pounded Yam",
      price: 1300,
      time: 20,
      img: "🥘",
      tag: "Chef's Pick",
      available: false,
    },
  ],
  "Cafe 2": [
    {
      id: 5,
      name: "Spaghetti + Sauce",
      price: 800,
      time: 10,
      img: "🍝",
      tag: "Budget Pick",
      available: true,
    },
    {
      id: 6,
      name: "Noodles + Egg",
      price: 600,
      time: 8,
      img: "🍜",
      tag: "Fast",
      available: true,
    },
    {
      id: 7,
      name: "Ofada Rice + Stew",
      price: 1400,
      time: 18,
      img: "🍱",
      tag: "Premium",
      available: true,
    },
    {
      id: 8,
      name: "Plantain + Beans",
      price: 700,
      time: 12,
      img: "🫘",
      tag: "",
      available: true,
    },
  ],
  "Cafe 3": [
    {
      id: 9,
      name: "Burger + Fries",
      price: 1500,
      time: 15,
      img: "🍔",
      tag: "Trending",
      available: true,
    },
    {
      id: 10,
      name: "Shawarma",
      price: 1200,
      time: 10,
      img: "🌯",
      tag: "Hot",
      available: true,
    },
    {
      id: 11,
      name: "Meat Pie + Juice",
      price: 600,
      time: 5,
      img: "🥧",
      tag: "Snack",
      available: true,
    },
    {
      id: 12,
      name: "Chicken Wings",
      price: 1800,
      time: 20,
      img: "🍗",
      tag: "Premium",
      available: false,
    },
  ],
  "Back of Cafe": [
    {
      id: 13,
      name: "Suya + Yam",
      price: 1000,
      time: 12,
      img: "🥩",
      tag: "Evening Fav",
      available: true,
    },
    {
      id: 14,
      name: "Corn + Pear",
      price: 400,
      time: 5,
      img: "🌽",
      tag: "Light",
      available: true,
    },
    {
      id: 15,
      name: "Bole + Fish",
      price: 900,
      time: 15,
      img: "🐟",
      tag: "Classic",
      available: true,
    },
    {
      id: 16,
      name: "Roasted Plantain",
      price: 500,
      time: 8,
      img: "🍌",
      tag: "",
      available: true,
    },
  ],
};
